export const AnalyticalEventNames = {
  IMAGE_SELECTION: 'Image selection',
  DRAWER_OPEN: 'Drawer opened',
  CLICK_SEARCH_ICON: 'Click search icon',
  CREATE: 'Create',
  EDIT: 'Edit',
  UPLOAD_INBOX: 'Upload inbox',
  EDIT_ITEM: 'Edit item',
  CREATE_ITEM: 'Create item',
  ADD_NEW_WORKLOG: 'Add new worklog',
  TIME_DURATION_CHANGE: 'Time duration change',
  APPROVAL_ACTION: 'Approval Action',
  ADD_A_NEW_COMMENT: 'Add a new comment',
  LOGOUT: 'Logout',
  SEARCH_FILTER: 'Search Filter',
  ENTER_SEARCH_TEXT: 'Enter search text',
};
