export const EntityType = {
    CUSTOMER_QUOTE : 'CUSTOMER_QUOTE',
    CUSTOMER_ORDER : 'CUSTOMER_ORDER',
    CUSTOMER : 'CUSTOMER',
    PROJECT : 'PROJECT',
    PRODUCT: 'PRODUCT',
    SELLER : 'SELLER',
    SUPPLIER : 'SUPPLIER',
    WORK_TYPE : 'WORK_TYPE',
    DEPARTMENT : 'DEPARTMENT',
    VAT_TYPE : 'VAT_TYPE',
    PHONEBOOK_SEARCH : 'PHONEBOOK_SEARCH',
    CURRENCY : 'CURRENCY',
    COUNTRY: 'COUNTRY',
    CUSTOMER_INVOICE: 'CUSTOMER_INVOICE',
    CUSTOMER_QUOTE: 'CUSTOMER_QUOTE',
    DELIVERY_TERMS: 'DELIVERY_TERMS',
    PAYMENT_TERMS: 'PAYMENT_TERMS'
};
