export const PermissionType = {
  UI_ACCOUNTING: 'ui_accounting',
  UI_ACCOUNTING_BILLS: 'ui_accounting_bills',
  UI_APPROVAL_ACCOUNTING: 'ui_approval_accounting',
  UI_TIMETRACKING: 'ui_timetracking',
  UI_ASSIGNMENTS: 'ui_assignments',
  UI_ASSIGNMENTS_APPROVALS: 'ui_assignments_approvals',
  UI_SALES_ALL: 'ui_sales_*',
  UI_SALES : 'ui_sales',
  UI_SALES_CUSTOMER: 'ui_sales_customer',
  UI_SALES_INVOICES: 'ui_sales_invoices',
  UI_SALES_ORDERS: 'ui_sales_orders',
  UI_SALES_PRODUCTGROUPS: 'ui_sales_productgroups',
  UI_SALES_PRODUCTS: 'ui_sales_products',
  UI_SALES_QUOTES: 'ui_sales_quotes',
  UI_SALES_REMINDERS: 'ui_sales_reminders',
  UI_SALES_REMINDERS_DEBTCOLLECTION: 'ui_sales_reminders_debtcollect',
  UI_SALES_REMINDERS_READY: 'ui_sales_reminders_ready',
  UI_SALES_REMINDERS_REMINDED: 'ui_sales_reminders_reminded',
  UI_SALES_SELLERS: 'ui_sales_sellers',
  UI_ADMIN : "ui_admin",
};
