# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Pods for UniEconomyMobile
  
target 'UniEconomyMobile' do
  pod 'AppCenter/Crashes', '~> 1.12.0'
  pod 'AppCenter/Analytics', '~> 1.12.0'
  pod 'AppCenterReactNativeShared', '~> 1.11.0'
  
  pod 'AppAuth', '>= 0.94'
  
  
  platform :ios, '9.0'
  target 'UniEconomyMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'UniEconomyMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UniEconomyMobile-tvOS

  target 'UniEconomyMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
